jobs:
- name: update-cloud-run
  on_failure:
    params:
      actionTarget: $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
      text: Job $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        failed
    put: teams
  on_success:
    params:
      actionTarget: $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
      text: Job $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        completed successfully
    put: teams
  plan:
  - in_parallel:
      steps:
      - get: ci-src
      - get: manifest-src
        trigger: true
      - get: ax360-bff-image
        trigger: true
  - file: ci-src/.concourse/tasks/cloudrun/cloudrun-deploy.yaml
    input_mapping:
      src: manifest-src
    params:
      MANIFEST_PATH: teams/ia-private-wealth/advisor-client-facing/dev/ax360.yaml
      PIPELINES_GCP_IMPERSONATESERVICEACCOUNT: terraform@iapw-acf-d-ax360-dev1-1000.iam.gserviceaccount.com
    task: update-cloud-run
- name: deploy-firebase
  plan:
  - in_parallel:
      steps:
      - get: ci-src
      - get: manifest-src
      - get: firebase-src
        trigger: true
  - file: ci-src/.concourse/tasks/npm-build/npm-build.yaml
    input_mapping:
      src: firebase-src
    output_mapping:
      src: firebase-src
    params:
      NPM_COMMAND: env-cmd -f .env npm run build
      NPM_ENV: |
        ENV=development
        CLOUD_DOC_ENDP=https://ax360-aorw4low.ue.gateway.dev
        CLOUD_RUN_ENDP=https://ax360-aorw4low.ue.gateway.dev
        CLOUD_ENDP=https://ax360-aorw4low.ue.gateway.dev
        FIREBASE_TOKEN_EP=https://ax360-aorw4low.ue.gateway.dev/auth/generate-firebase-token
        API_KEY=AIzaSyB3PpEZcser9ffPit45i6etTNBP0AMrc_Y
        AUTH_DOMAIN=iapw-acf-d-ax360-dev1-1000.firebaseapp.com
        PROJECT_ID=iapw-acf-d-ax360-dev1-1000
        STORAGE_BUCKET=iapw-acf-d-ax360-dev1-1000.appspot.com
        MESSAGING_SENDER_ID=837570966224
        APP_ID=1:837570966224:web:2315b49ca4b28f5e45e4d5
        LOOKER_URL=https://iapw.cloud.looker.com
        LOOKER_INSTANCE=https://iapw.cloud.looker.com
        MEASURE_ID=G-L8E8BN2DZ0
        MIRROR_VIEW_URL=https://iasa.accp.secureweb.ia.ca/FWMWPNS1/mirrorview
        OKTA_CLIENT_ID=0oa88adko0CsqIf311d7
        OKTA_ISSUER=https://login.dev.privatewealth.ia.ca/oauth2/default
        OKTA_AUTH_URL=https://login.dev.privatewealth.ia.ca/oauth2/default/v1/authorize
        OKTA_ACCESS_TOKEN_URL=https://login.dev.privatewealth.ia.ca/oauth2/default/v1/token
      NPM_INSTALL_ARGS: --legacy-peer-deps
      NPM_PATH: ""
    task: npm-build
  - file: ci-src/.concourse/tasks/firebase-deploy/firebase-deploy.yaml
    input_mapping:
      src: firebase-src
    output_mapping:
      src: firebase-src
    params:
      FIREBASE_APP_PATH: ""
      FIREBASE_CONFIG: ""
      GCP_PROJECT_ID: iapw-acf-d-ax360-dev1-1000
      GOOGLE_IMPERSONATE_SERVICE_ACCOUNT: terraform@iapw-acf-d-ax360-dev1-1000.iam.gserviceaccount.com
    task: firebase-deploy
- name: terraform-apply-api-gateway
  on_failure:
    params:
      actionTarget: $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
      text: Job $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        failed
    put: teams
  on_success:
    params:
      actionTarget: $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
      text: Job $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        completed successfully
    put: teams
  plan:
  - in_parallel:
      steps:
      - get: ci-src
      - get: manifest-src
        trigger: true
      - get: terraform-api-gateway-src
        trigger: true
  - file: ci-src/.concourse/tasks/terraform-deployment/terraform-deployment-apply.yaml
    input_mapping:
      src: terraform-api-gateway-src
    params:
      GCP_PROJECT_ID: iapw-acf-d-ax360-dev1-1000
      GOOGLE_IMPERSONATE_SERVICE_ACCOUNT: terraform@iapw-acf-d-ax360-dev1-1000.iam.gserviceaccount.com
      MANIFEST_PATH: teams/ia-private-wealth/advisor-client-facing/dev/ax360.yaml
      TERRAFORM_BACKEND_GCS_BUCKET: iapw-acf-d-ax360-dev1-1000
      TERRAFORM_DIRECTORY: teams/ia-private-wealth/advisor-client-facing/terraform/ax360-api-gateway
      TERRAFORM_GROUP_NAME: api-gateway
      TERRAFORM_PREFIX: advisor-client-facing-dev-ax360-api-gateway
    task: terraform-apply
- name: terraform-apply-firestore
  on_failure:
    params:
      actionTarget: $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
      text: Job $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        failed
    put: teams
  on_success:
    params:
      actionTarget: $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
      text: Job $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        completed successfully
    put: teams
  plan:
  - in_parallel:
      steps:
      - get: ci-src
      - get: manifest-src
        trigger: true
      - get: terraform-firestore-src
        trigger: true
  - file: ci-src/.concourse/tasks/terraform-deployment/terraform-deployment-apply.yaml
    input_mapping:
      src: terraform-firestore-src
    params:
      GCP_PROJECT_ID: iapw-acf-d-ax360-dev1-1000
      GOOGLE_IMPERSONATE_SERVICE_ACCOUNT: terraform@iapw-acf-d-ax360-dev1-1000.iam.gserviceaccount.com
      MANIFEST_PATH: teams/ia-private-wealth/advisor-client-facing/dev/ax360.yaml
      TERRAFORM_BACKEND_GCS_BUCKET: iapw-acf-d-ax360-dev1-1000
      TERRAFORM_DIRECTORY: teams/ia-private-wealth/advisor-client-facing/terraform/ax360-firestore
      TERRAFORM_GROUP_NAME: firestore
      TERRAFORM_PREFIX: advisor-client-facing-dev-ax360-firestore
    task: terraform-apply
- name: terraform-apply-cloud-storage
  on_failure:
    params:
      actionTarget: $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
      text: Job $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        failed
    put: teams
  on_success:
    params:
      actionTarget: $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
      text: Job $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        completed successfully
    put: teams
  plan:
  - in_parallel:
      steps:
      - get: build-metadata
      - get: ci-src
      - get: manifest-src
        trigger: true
      - get: terraform-cloud-storage-src
        trigger: true
  - file: ci-src/.concourse/tasks/terraform-deployment/terraform-deployment-apply.yaml
    input_mapping:
      src: terraform-cloud-storage-src
    params:
      GCP_PROJECT_ID: iapw-acf-d-ax360-dev1-1000
      GITHUB_REPOSITORY: ia-mgcp/ia-iac-deployments
      GOOGLE_IMPERSONATE_SERVICE_ACCOUNT: terraform@iapw-acf-d-ax360-dev1-1000.iam.gserviceaccount.com
      MANIFEST_PATH: teams/ia-private-wealth/advisor-client-facing/dev/ax360.yaml
      PIPELINES_SERVER: https://pipelines.ci.ia-mgcp.ca
      PIPELINES_SERVER_USERNAME: ci
      TERRAFORM_BACKEND_GCS_BUCKET: iapw-acf-d-ax360-dev1-1000
      TERRAFORM_DIRECTORY: teams/ia-private-wealth/advisor-client-facing/terraform/ax360-cloudstorage
      TERRAFORM_GROUP_NAME: cloud-storage
      TERRAFORM_PREFIX: advisor-client-facing-dev-ax360-cloud-storage
    task: terraform-apply
- name: terraform-apply-firestore-collection
  on_failure:
    params:
      actionTarget: $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
      text: Job $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        failed
    put: teams
  on_success:
    params:
      actionTarget: $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
      text: Job $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        completed successfully
    put: teams
  plan:
  - in_parallel:
      steps:
      - get: ci-src
      - get: manifest-src
        trigger: true
      - get: terraform-firestore-collection-src
        trigger: true
  - file: ci-src/.concourse/tasks/terraform-deployment/terraform-deployment-apply.yaml
    input_mapping:
      src: terraform-firestore-collection-src
    params:
      GCP_PROJECT_ID: iapw-acf-d-ax360-dev1-1000
      GOOGLE_IMPERSONATE_SERVICE_ACCOUNT: terraform@iapw-acf-d-ax360-dev1-1000.iam.gserviceaccount.com
      MANIFEST_PATH: teams/ia-private-wealth/advisor-client-facing/dev/ax360.yaml
      TERRAFORM_BACKEND_GCS_BUCKET: iapw-acf-d-ax360-dev1-1000
      TERRAFORM_DIRECTORY: teams/ia-private-wealth/advisor-client-facing/terraform/ax360-firestore-collection
      TERRAFORM_GROUP_NAME: firestore-collection
      TERRAFORM_PREFIX: advisor-client-facing-dev-ax360-firestore-collection
    task: terraform-apply
resource_types:
- name: teams-notification
  source:
    repository: navicore/teams-notification-resource
    tag: latest
  type: docker-image
- name: build-metadata
  source:
    repository: swce/metadata-resource
    tag: latest
  type: docker-image
resources:
- name: ax360-bff-image
  source:
    password: ((terraform.googleCredentials))
    repository: gcr.io/prj-iapw-cicd-c-cicd-vld4/iapw_cloud_run/iapw-ax360-bff
    tag: latest
    username: _json_key
  type: registry-image
- name: build-metadata
  type: build-metadata
- name: ci-src
  source:
    branch: pipelines-server
    paths:
    - .concourse
    private_key: ((git.ssh-private-key))
    uri: git@github.com:paasas/paasas-pipelines.git
  type: git
- name: firebase-src
  source:
    branch: development
    private_key: ((git.ssh-private-key))
    uri: git@github.com:ia-mgcp/ax360-development.git
  type: git
- name: manifest-src
  source:
    branch: main
    paths:
    - teams/ia-private-wealth/advisor-client-facing/dev/ax360.yaml
    private_key: ((git.ssh-private-key))
    uri: git@github.com:ia-mgcp/ia-iac-deployments.git
  type: git
- name: teams
  source:
    url: ((teams.webhookUrl))
  type: teams-notification
- name: terraform-api-gateway-src
  source:
    branch: main
    paths:
    - teams/ia-private-wealth/advisor-client-facing/terraform/ax360-api-gateway
    private_key: ((git.ssh-private-key))
    uri: git@github.com:ia-mgcp/ia-iac-deployments.git
  type: git
- name: terraform-cloud-storage-src
  source:
    branch: main
    paths:
    - teams/ia-private-wealth/advisor-client-facing/terraform/ax360-cloudstorage
    private_key: ((git.ssh-private-key))
    uri: git@github.com:ia-mgcp/ia-iac-deployments.git
  type: git
- name: terraform-firestore-collection-src
  source:
    branch: main
    paths:
    - teams/ia-private-wealth/advisor-client-facing/terraform/ax360-firestore-collection
    private_key: ((git.ssh-private-key))
    uri: git@github.com:ia-mgcp/ia-iac-deployments.git
  type: git
- name: terraform-firestore-src
  source:
    branch: main
    paths:
    - teams/ia-private-wealth/advisor-client-facing/terraform/ax360-firestore
    private_key: ((git.ssh-private-key))
    uri: git@github.com:ia-mgcp/ia-iac-deployments.git
  type: git
