---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: harbor.paasas.io/public/paasas-pipelines
    tag: latest

inputs:
- name: src
- name: ci-src

outputs:
- name: pipelines

params:
  MANIFEST_PATH:
  PIPELINES_CONCOURSE_DEPLOYMENTPATHPREFIX: 
  PIPELINES_CONCOURSE_DEPLOYMENTSRCURI: 
  PIPELINES_CONCOURSE_DEPLOYMENTTERRAFORMBACKENDBUCKETSUFFIX: 
  PIPELINES_CONCOURSE_GITHUBREPOSITORY: 
  PIPELINES_CONCOURSE_GITHUBEMAIL: 
  PIPELINES_CONCOURSE_GITHUBUSERNAME: 
  PIPELINES_CONCOURSE_PLATFORMPATHPREFIX: 
  PIPELINES_CONCOURSE_PLATFORMSRCURI: 
  PIPELINES_CONCOURSE_TERRAFORMBACKENDGCSBUCKET: 
  PIPELINES_CONCOURSE_TERRAFORMBACKENDPREFIX: 
  PIPELINES_CONCOURSE_TERRAFORMSRCBRANCH: 
  PIPELINES_CONCOURSE_TERRAFORMSRCURI:  
  PIPELINES_GCP_IMPERSONATESERVICEACCOUNT: 
  TARGET: 

run:
  path: ci-src/.concourse/tasks/deployment/update-deployment-pipeline.sh