---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: andreysenov/firebase-tools
    tag: latest

inputs:
- name: src
- name: ci-src

params:
  GCP_PROJECT_ID: 
  GOOGLE_IMPERSONATE_SERVICE_ACCOUNT: 
  FIREBASE_APP_PATH: 
  FIREBASE_CONFIG: 

run:
  path: ci-src/.concourse/tasks/firebase-deploy/firebase-deploy.sh