---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: harbor.paasas.io/public/paasas-firebase
    tag: latest

inputs:
- name: ci-src
- name: src

params:
  GCP_PROJECT_ID: 
  GOOGLE_CREDENTIALS: ((terraform.googleCredentials))
  GOOGLE_IMPERSONATE_SERVICE_ACCOUNT: 
  FIREBASE_APP_PATH:  
  FIREBASE_CONFIG: 

run:
  path: ci-src/.concourse/tasks/firebase-deploy/firebase-deploy.sh