---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: paasas/ci
    tag: latest

inputs:
- name: ci-src
- name: dags-src

params:
  COMPOSER_DAGS_BUCKET_NAME: 
  COMPOSER_DAGS_BUCKET_PATH: 
  COMPOSER_DAGS_PATH: 
  COMPOSER_FLEX_TEMPLATES: 
  GOOGLE_CREDENTIALS: ((terraform.googleCredentials))
  GOOGLE_IMPERSONATE_SERVICE_ACCOUNT: 

run:
  path: ci-src/.concourse/tasks/composer-update-dags/composer-update-dags.sh