---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: harbor.paasas.io/public/paasas-terraform
    tag: 1.3.8

inputs:
- name: ci-src
- name: src
- name: terraform-lts-src
- name: terraform-next-src

outputs:
- name: terraform-state

caches:
- path: .terraform

params:
  SOURCE_PATH:  
run:
  path: ci-src/.concourse/tasks/terraform-apply/terraform-apply.sh