resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: ci-src
  type: git
  source:
    uri: git@github.com:daniellavoie/infra-as-code-demo.git
    private_key: ((git.ssh-private-key))
    branch: main
    paths:
    - .concourse
- name: terraform-lts-src
  type: git
  source:
    uri: git@github.com:daniellavoie/infra-as-code-demo.git
    private_key: ((git.ssh-private-key))
    branch: v2
    paths:
    - terraform/infra/lts
- name: terraform-next-src
  type: git
  source:
    uri: git@github.com:daniellavoie/infra-as-code-demo.git
    private_key: ((git.ssh-private-key))
    branch: v2
    paths:
    - terraform/infra/next
- name: ax360-frontend-dev-platform-pr
  type: pull-request
  source:
    access_token: ((github.accessToken))
    repository: paasas/paasas-pipelines
    paths:
    - teams/ax360/frontend/dev.yaml

- name: ax360-frontend-dev-platform-src
  type: git
  source:
    uri: git@github.com:daniellavoie/infra-as-code-demo.git
    private_key: ((git.ssh-private-key))
    branch: v2
    paths:
    - teams/ax360/frontend/dev.yaml
- name: ax360-frontend-prod-platform-pr
  type: pull-request
  source:
    access_token: ((github.accessToken))
    repository: paasas/paasas-pipelines
    paths:
    - teams/ax360/frontend/dev.yaml

- name: ax360-frontend-prod-platform-src
  type: git
  source:
    uri: git@github.com:daniellavoie/infra-as-code-demo.git
    private_key: ((git.ssh-private-key))
    branch: v2
    paths:
    - teams/ax360/frontend/dev.yaml
- name: ax360-frontend-staging-platform-pr
  type: pull-request
  source:
    access_token: ((github.accessToken))
    repository: paasas/paasas-pipelines
    paths:
    - teams/ax360/frontend/dev.yaml

- name: ax360-frontend-staging-platform-src
  type: git
  source:
    uri: git@github.com:daniellavoie/infra-as-code-demo.git
    private_key: ((git.ssh-private-key))
    branch: v2
    paths:
    - teams/ax360/frontend/dev.yaml

jobs:
- name: ax360-frontend-dev-terraform-apply
  plan:
  - in_parallel:
    - get: ax360-frontend-dev-platform-src
      trigger: true
    - get: ci-src
    - get: terraform-lts-src
    - get: terraform-next-src
  - task: terraform-apply
    file: ci-src/.concourse/tasks/terraform-apply/terraform-apply.yml
    input_mapping:
      src: src-staging
    params:
      PLATFORM_MANIFEST_PATH: teams/ax360/frontend/dev.yaml

- name: ax360-frontend-dev-terraform-plan
  plan:
  - in_parallel:
    - get: ax360-frontend-dev-platform-pr
      trigger: true
    - get: ci-src
  - in_parallel:
    - put: ax360-frontend-dev-platform-pr
      params:
        path: ax360-frontend-dev-platform-pr
        status: pending
    - get: terraform-lts-src
    - get: terraform-next-src
  - task: terraform-plan
    file: ci-src/.concourse/tasks/terraform-plan/terraform-plan.yml
    input_mapping:
      src: ax360-frontend-dev-platform-pr
    params:
      PLATFORM_MANIFEST_PATH: teams/ax360/frontend/dev.yaml
  - put: ax360-frontend-dev-platform-pr
    params:
      comment_file: terraform-out/plan.md
      path: ax360-frontend-dev-platform-pr
      status: success
  on_failure:
    do:
    - put: ax360-frontend-dev-platform-pr
      params:
        path: ax360-frontend-dev-infra-pr
        status: failure
- name: ax360-frontend-prod-terraform-apply
  plan:
  - in_parallel:
    - get: ax360-frontend-prod-platform-src
      trigger: true
    - get: ci-src
    - get: terraform-lts-src
    - get: terraform-next-src
  - task: terraform-apply
    file: ci-src/.concourse/tasks/terraform-apply/terraform-apply.yml
    input_mapping:
      src: src-staging
    params:
      PLATFORM_MANIFEST_PATH: teams/ax360/frontend/dev.yaml

- name: ax360-frontend-prod-terraform-plan
  plan:
  - in_parallel:
    - get: ax360-frontend-prod-platform-pr
      trigger: true
    - get: ci-src
  - in_parallel:
    - put: ax360-frontend-prod-platform-pr
      params:
        path: ax360-frontend-prod-platform-pr
        status: pending
    - get: terraform-lts-src
    - get: terraform-next-src
  - task: terraform-plan
    file: ci-src/.concourse/tasks/terraform-plan/terraform-plan.yml
    input_mapping:
      src: ax360-frontend-prod-platform-pr
    params:
      PLATFORM_MANIFEST_PATH: teams/ax360/frontend/dev.yaml
  - put: ax360-frontend-prod-platform-pr
    params:
      comment_file: terraform-out/plan.md
      path: ax360-frontend-prod-platform-pr
      status: success
  on_failure:
    do:
    - put: ax360-frontend-prod-platform-pr
      params:
        path: ax360-frontend-prod-infra-pr
        status: failure
- name: ax360-frontend-staging-terraform-apply
  plan:
  - in_parallel:
    - get: ax360-frontend-staging-platform-src
      trigger: true
    - get: ci-src
    - get: terraform-lts-src
    - get: terraform-next-src
  - task: terraform-apply
    file: ci-src/.concourse/tasks/terraform-apply/terraform-apply.yml
    input_mapping:
      src: src-staging
    params:
      PLATFORM_MANIFEST_PATH: teams/ax360/frontend/dev.yaml

- name: ax360-frontend-staging-terraform-plan
  plan:
  - in_parallel:
    - get: ax360-frontend-staging-platform-pr
      trigger: true
    - get: ci-src
  - in_parallel:
    - put: ax360-frontend-staging-platform-pr
      params:
        path: ax360-frontend-staging-platform-pr
        status: pending
    - get: terraform-lts-src
    - get: terraform-next-src
  - task: terraform-plan
    file: ci-src/.concourse/tasks/terraform-plan/terraform-plan.yml
    input_mapping:
      src: ax360-frontend-staging-platform-pr
    params:
      PLATFORM_MANIFEST_PATH: teams/ax360/frontend/dev.yaml
  - put: ax360-frontend-staging-platform-pr
    params:
      comment_file: terraform-out/plan.md
      path: ax360-frontend-staging-platform-pr
      status: success
  on_failure:
    do:
    - put: ax360-frontend-staging-platform-pr
      params:
        path: ax360-frontend-staging-infra-pr
        status: failure

groups:
- name: ax360-frontend-dev
  jobs:
  - ax360-frontend-dev-terraform-plan
  - ax360-frontend-dev-terraform-apply

- name: ax360-frontend-prod
  jobs:
  - ax360-frontend-prod-terraform-plan
  - ax360-frontend-prod-terraform-apply

- name: ax360-frontend-staging
  jobs:
  - ax360-frontend-staging-terraform-plan
  - ax360-frontend-staging-terraform-apply
