---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: paasas/paasas-terraform
    tag: 1.5.2

inputs:
- name: ci-src
- name: manifest-src
- name: src

outputs:
- name: terraform-state
- name: terraform-out

caches:
- path: .terraform

params:
  GCP_PROJECT_ID: 
  GOOGLE_CREDENTIALS: ((terraform.googleCredentials))
  MANIFEST_PATH: 
  TARGET: 
  TERRAFORM_BACKEND_GCS_BUCKET: 
  TERRAFORM_COMMAND: plan
  TERRAFORM_DIRECTORY: 
  TERRAFORM_FLAGS: -input=false -no-color
  TERRAFORM_GROUP_NAME: 
  TERRAFORM_PREFIX: 
run:
  path: ci-src/.concourse/tasks/terraform-deployment/terraform-deployment.sh