---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: paasas/paasas-terraform
    tag: 1.5.6

inputs:
- name: build-metadata
- name: ci-src
- name: manifest-src
- name: src

outputs:
- name: terraform-state
- name: terraform-out

caches:
- path: .terraform

params:  
  GCP_PROJECT_ID: 
  GITHUB_REPOSITORY: 
  GOOGLE_CREDENTIALS: ((terraform.googleCredentials))
  GOOGLE_IMPERSONATE_SERVICE_ACCOUNT:
  MANIFEST_PATH: 
  PIPELINES_SERVER: 
  PIPELINES_SERVER_USERNAME: 
  PIPELINES_SERVER_PASSWORD: ((pipelines.password))
  TERRAFORM_BACKEND_GCS_BUCKET: 
  TERRAFORM_COMMAND: apply 
  TERRAFORM_DIRECTORY: 
  TERRAFORM_FLAGS: -input=false -no-color -auto-approve
  TERRAFORM_GROUP_NAME: 
  TERRAFORM_PREFIX: 
run:
  path: ci-src/.concourse/tasks/terraform-deployment/terraform-deployment.sh