---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: harbor.paasas.io/public/ci
    tag: latest

inputs:
- name: ci-src
- name: src

params:
  TRIGGER_NAME: 
  PROJECT: 
  REGION: 
  IMPERSONATE_SERVICE_ACCOUNT: 

run:
  path: ci-src/.concourse/tasks/run-cloud-build-liquibase-trigger/run-cloud-build-liquibase-trigger.sh