---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: harbor.paasas.io/public/ci
    tag: latest

inputs:
- name: ci-src
- name: composer-variables-src

params:
  COMPOSER_DAGS_BUCKET_NAME: 
  COMPOSER_DAGS_BUCKET_PATH:
  COMPOSER_ENVIRONMENT_NAME: 
  COMPOSER_LOCATION: 
  COMPOSER_PROJECT: 
  COMPOSER_VARIABLES_PATH: 
  GOOGLE_CREDENTIALS: ((terraform.googleCredentials))
  GOOGLE_IMPERSONATE_SERVICE_ACCOUNT: 

run:
  path: ci-src/.concourse/tasks/composer-update-variables/composer-update-variables.sh