---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: paasas/ci
    tag: latest

inputs:
- name: ci-src
- name: dags-src

params:
  COMPOSER_FLEX_TEMPLATES_TARGET_PATH: 
  COMPOSER_FLEX_TEMPLATES_VERSION: 
  COMPOSER_FLEX_TEMPLATES_IMAGE: 
  COMPOSER_FLEX_TEMPLATES_METADATA: 
  GOOGLE_CREDENTIALS: ((terraform.googleCredentials))
  GOOGLE_IMPERSONATE_SERVICE_ACCOUNT: 

run:
  path: ci-src/.concourse/tasks/composer-update-dags/composer-update-flex-templates.sh