---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: paasas/paasas-pipelines
    tag: latest

inputs:
- name: ci-src
- name: src

params:
  MANIFEST_PATH: 
  PIPELINES_GCP_CREDENTIALSJSON: ((gcp.credentials))
  PIPELINES_GCP_IMPERSONATESERVICEACCOUNT: 

run:
  path: ci-src/.concourse/tasks/cloudrun/cloudrun-deploy.sh