---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: harbor.paasas.io/public/ci
    tag: latest

inputs:
- name: ci-src
- name: platform-manifest-src

outputs:
- name: terraform-state
- name: terraform-out

caches:
- path: .terraform

params:
  MANIFEST_PATH: 
  GOOGLE_CREDENTIALS: ((gcp.credentials))

run:
  path: ci-src/.concourse/tasks/cloudrun/cloudrun-deploy.sh