---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: harbor.paasas.io/public/paasas-pipelines
    tag: latest

inputs:
- name: ci-src
- name: src

params:
  MANIFEST_PATH: 
  PIPELINES_CLOUDRUN_GOOGLECREDENTIALSJSON: ((gcp.credentials))

run:
  path: ci-src/.concourse/tasks/cloudrun/cloudrun-deploy.sh