---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: paasas/ci
    tag: latest

inputs:
- name: ci-src
- name: metadata
- name: src
- name: test-reports-src

outputs:
- name: version

caches: 
- path: src/m2

params:
  ENV_VARIABLES_SECRET_MANAGER_KEY_NAME: TESTS_ENV_VARIABLES
  GIT_PRIVATE_KEY: 
  GIT_USER_EMAIL: 
  GIT_USER_NAME: 
  GOOGLE_CREDENTIALS: ((terraform.googleCredentials))
  GOOGLE_IMPERSONATE_SERVICE_ACCOUNT: 
  GOOGLE_PROJECT_ID: 
  MVN_REPOSITORY_PASSWORD: ((github.accessToken))
  MVN_REPOSITORY_USERNAME: 
  TEST_REPORTS_GIT_BRANCH: gh-pages
  
run:
  path: ci-src/.concourse/tasks/maven-test/maven-test.sh