---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: harbor.paasas.io/public/java-ci
    tag: latest

inputs:
- name: ci-src
- name: src

outputs:
- name: version

caches: 
- path: src/m2

params:
  MVN_REPOSITORY_URL: https://maven.pkg.github.com/ia-mgcp/ax360-automation-tests-framework
  MVN_REPOSITORY_USERNAME: 
  MVN_REPOSITORY_PASSWORD: ((github.accessToken))
  
run:
  path: ci-src/.concourse/tasks/maven-test/maven-test.sh