---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: harbor.paasas.io/public/paasas-pipelines
    tag: latest

inputs:
- name: platforms-src
- name: ci-src

outputs:
- name: pipelines

params:
  TARGETS_DIRECTORY: 
  TERRAFORM_BACKEND_GCS_BUCKET: 

run:
  path: ci-src/.concourse/tasks/generate-platform-pipelines/generate-platform-pipelines.sh