resources:
- name: src
  type: git
  source: 
    uri: git@github.com:paasas/paasas-pipelines.git
    private_key: ((git.ssh-private-key))
    branch: main
    ignore_paths:
    - .concourse
    
- name: ci-src
  type: git
  source: 
    uri: git@github.com:paasas/paasas-pipelines.git
    private_key: ((git.ssh-private-key))
    branch: main
    paths:
    - .concourse

- name: paasas-pipelines-release
  type: github-release
  source:
    access_token: ((github.accessToken))
    owner: paasas
    repository: paasas-pipelines

- name: paasas-pipelines-image-src
  type: git
  source: 
    uri: git@github.com:paasas/paasas-pipelines.git
    private_key: ((git.ssh-private-key))
    branch: main
    paths:
    - .concourse/images/paasas-pipelines

- name: paasas-pipelines-image
  type: docker-image
  source:
    repository: ((registry.publicUrl))/paasas-pipelines
    username: ((registry.username))
    password: ((registry.password))

jobs:
- name: publish-paasas-pipelines
  plan:
  - in_parallel:
    - get: src
      trigger: true
      version: every
    - get: ci-src
  - task: build
    file: ci-src/.concourse/tasks/build/build.yaml
  - in_parallel:
    - put: paasas-pipelines-release
      params:
        name: version/version
        tag: version/version
        globs:
        - build/pipelines-concourse
    - task: prepare-build-args
      config:
        platform: linux
        image_resource:
          type: registry-image
          source: 
            repository: busybox
        inputs:
        - name: ci-src
        - name: build
        - name: paasas-pipelines-image-src
        outputs:
        - name: build-args
        - name: paasas-pipelines-image-src
        run:
          path: ci-src/.concourse/images/paasas-pipelines/prepare-docker-build.sh
    - put: paasas-pipelines-image
      params: 
        build: paasas-pipelines-image-src/.concourse/images/paasas-pipelines
        tag_as_latest: true
        tag_file: paasas-pipelines-release/version
        build_args_file: build-args/build-args.json
      get_params: 
        skip_download: true