resources:
- name: paasas-terraform-image-src
  type: git
  source: 
    uri: git@github.com:paasas/paasas-pipelines.git
    private_key: ((git.ssh-private-key))
    branch: main
    paths:
    - .concourse/images/paasas-terraform

- name: terraform-image
  type: docker-image
  source:
    repository: hashicorp/terraform

- name: paasas-terraform-image
  type: docker-image
  source:
    repository: ((registry.publicUrl))/paasas-terraform
    username: ((registry.username))
    password: ((registry.password))

jobs:
- name: publish-paasas-terraform-image
  plan:
  - in_parallel:
    - get: terraform-image
      trigger: true
      version: every
      params:
        skip_download: true
    - get: paasas-terraform-image-src
      trigger: true
  - task: prepare-build-args
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: 
          repository: busybox
      inputs:
      - name: paasas-terraform-image-src
      - name: terraform-image
      outputs: 
      - name: "build-args"
      run:
        path: paasas-terraform-image-src/.concourse/images/paasas-terraform/prepare-build-args.sh
  - put: paasas-terraform-image
    params: 
      build: paasas-terraform-image-src/.concourse/images/paasas-terraform
      tag_as_latest: true
      tag_file: terraform-image/tag
      build_args_file: build-args/build-args.json
    get_params: 
      skip_download: true

display:
  background_image: https://64.media.tumblr.com/d5cc2ecd26a4d02a840d5a91f515c318/tumblr_n04563a3vR1qj86bro1_500.gifv