resources:
- name: paasas-graal-vm-image-src
  type: git
  source: 
    uri: git@github.com:paasas/paasas-pipelines.git
    private_key: ((git.ssh-private-key))
    branch: main
    paths:
    - .concourse/images/paasas-graal-vm
- name: paasas-firebase-image-src
  type: git
  source: 
    uri: git@github.com:paasas/paasas-pipelines.git
    private_key: ((git.ssh-private-key))
    branch: main
    paths:
    - .concourse/images/paasas-firebase
    
- name: paasas-terraform-image-src
  type: git
  source: 
    uri: git@github.com:paasas/paasas-pipelines.git
    private_key: ((git.ssh-private-key))
    branch: main
    paths:
    - .concourse/images/paasas-terraform

- name: terraform-release
  type: github-release
  source:
    owner: hashicorp
    repository: terraform
    access_token: ((github.accessToken))

- name: paasas-terraform-image
  type: docker-image
  source:
    repository: paasas/paasas-terraform
    username: ((dockerhub.username))
    password: ((dockerhub.password))

- name: paasas-firebase-image
  type: docker-image
  source:
    repository: paasas/paasas-firebase
    username: ((dockerhub.username))
    password: ((dockerhub.password))

- name: paasas-graal-vm-image
  type: docker-image
  source:
    repository: paasas/paasas-graal-vm
    username: ((dockerhub.username))
    password: ((dockerhub.password))

jobs:
- name: paasas-firebase
  plan:
  - get: paasas-firebase-image-src
    trigger: true
  - put: paasas-firebase-image
    params: 
      build: paasas-firebase-image-src/.concourse/images/paasas-firebase
      tag_as_latest: true
    get_params: 
      skip_download: true

- name: paasas-graal-vm
  plan:
  - get: paasas-graal-vm-image-src
    trigger: true
  - put: paasas-graal-vm-image
    params: 
      build: paasas-graal-vm-image-src/.concourse/images/paasas-graal-vm
      tag_as_latest: true
    get_params: 
      skip_download: true

- name: publish-paasas-terraform-image
  plan:
  - in_parallel:
    - get: terraform-release
      trigger: true
      version: every
      params:
        skip_download: true
    - get: paasas-terraform-image-src
      trigger: true
  - task: prepare-build-args
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: 
          repository: busybox
      inputs:
      - name: paasas-terraform-image-src
      - name: terraform-release
      outputs: 
      - name: "build-args"
      run:
        path: paasas-terraform-image-src/.concourse/images/paasas-terraform/prepare-build-args.sh
  - put: paasas-terraform-image
    params: 
      build: paasas-terraform-image-src/.concourse/images/paasas-terraform
      tag_as_latest: true
      tag_file: terraform-release/version
      build_args_file: build-args/build-args.json
    get_params: 
      skip_download: true

display:
  background_image: https://64.media.tumblr.com/d5cc2ecd26a4d02a840d5a91f515c318/tumblr_n04563a3vR1qj86bro1_500.gifv