resources:
- name: paasas-pipelines-src
  type: git
  source: 
    uri: git@github.com:paasas/paasas-pipelines.git
    private_key: ((git.ssh-private-key))
    branch: main
    paths:
    - .concourse/pipelines/paasas-pipelines.yaml
    
- name: docker-images-src
  type: git
  source: 
    uri: git@github.com:paasas/paasas-pipelines.git
    private_key: ((git.ssh-private-key))
    branch: main
    paths:
    - .concourse/pipelines/docker-images.yaml
    
- name: platform-demo-pipelines-src
  type: git
  source: 
    uri: git@github.com:paasas/paasas-pipelines.git
    private_key: ((git.ssh-private-key))
    branch: main
    paths:
    - .concourse/pipelines/platforms-demo-pipelines.yaml

jobs:
- name: paasas-pipelines
  plan:
  - get: paasas-pipelines-src
    trigger: true
  - set_pipeline: paasas-pipelines
    file: paasas-pipelines-src/.concourse/pipelines/paasas-pipelines.yaml
    
- name: docker-images
  plan:
  - get: docker-images-src
    trigger: true
  - set_pipeline: docker-images
    file: docker-images-src/.concourse/pipelines/docker-images.yaml
    
- name: platform-demo-pipelines
  plan:
  - get: platform-demo-pipelines-src
    trigger: true
  - set_pipeline: platform-demo-pipelines
    file: platform-demo-pipelines-src/.concourse/pipelines/platforms-demo-pipelines.yaml