resources:
- name: ci-src
  type: git
  source:
    uri: git@github.com:paasas/paasas-pipelines.git
    private_key: ((git.ssh-private-key))
    branch: main
    paths:
    - .concourse

- name: platforms-src
  type: git
  source:
    uri: git@github.com:daniellavoie/infra-as-code-demo.git
    private_key: ((git.ssh-private-key))
    branch: main
    paths:
    - teams

jobs:
- name: update-pipelines
  plan:
  - in_parallel:
    - get: platforms-src
      trigger: true
    - get: ci-src
  - task: generate-pipelines
    file: ci-src/.concourse/tasks/generate-platform-pipelines/generate-platform-pipelines.yaml
    params:
      TARGETS_DIRECTORY: teams
      TERRAFORM_BACKEND_GCS_BUCKET: fx-demo-terraform-states
  - set_pipeline: platforms-demo
    file: pipelines/pipelines.yaml